/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module \$paramod\traffic_timer\WIDTH=s32'00000000000000000000000000001000 (clk, reset, timer_limit, timer_done);
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire [7:0] _04_;
  input clk;
  wire clk;
  reg [7:0] counter;
  input reset;
  wire reset;
  output timer_done;
  wire timer_done;
  input [7:0] timer_limit;
  wire [7:0] timer_limit;
  assign _00_ = counter + 1'h1;
  always @(posedge clk)
    if (_01_) counter <= 8'h00;
    else counter <= _00_;
  assign _01_ = | { timer_done, reset };
  assign _02_ = ! timer_limit;
  assign _03_ = counter == _04_;
  assign timer_done = _02_ || _03_;
  assign _04_ = timer_limit - 1'h1;
endmodule

module traffic_fsm(clk, reset, timer_done, NS_RED, NS_YELLOW, NS_GREEN, EW_RED, EW_YELLOW, EW_GREEN, current_state);
  wire [2:0] _00_;
  wire [2:0] _01_;
  wire [2:0] _02_;
  wire [2:0] _03_;
  wire [2:0] _04_;
  wire [2:0] _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  output EW_GREEN;
  wire EW_GREEN;
  output EW_RED;
  wire EW_RED;
  output EW_YELLOW;
  wire EW_YELLOW;
  output NS_GREEN;
  wire NS_GREEN;
  output NS_RED;
  wire NS_RED;
  output NS_YELLOW;
  wire NS_YELLOW;
  input clk;
  wire clk;
  output [2:0] current_state;
  reg [2:0] current_state;
  wire [2:0] next_state;
  input reset;
  wire reset;
  input timer_done;
  wire timer_done;
  always @(posedge clk)
    if (reset) current_state <= 3'h0;
    else if (_12_) current_state <= next_state;
  assign _06_ = { _15_, timer_done } != 2'h2;
  assign _07_ = { _16_, timer_done } != 2'h2;
  assign _08_ = { _17_, timer_done } != 2'h2;
  assign _09_ = { _18_, timer_done } != 2'h2;
  assign _10_ = { _19_, timer_done } != 2'h2;
  assign _11_ = { _20_, timer_done } != 2'h2;
  assign _12_ = & { _06_, _07_, _08_, _09_, _10_, _11_ };
  assign _13_ = | { _16_, _15_ };
  assign _14_ = | { _19_, _18_ };
  assign _01_ = timer_done ? 3'h2 : 3'hx;
  assign _00_ = timer_done ? 3'h1 : 3'hx;
  function [2:0] _33_;
    input [2:0] a;
    input [17:0] b;
    input [5:0] s;
    casez (s) // synopsys parallel_case
      6'b?????1:
        _33_ = b[2:0];
      6'b????1?:
        _33_ = b[5:3];
      6'b???1??:
        _33_ = b[8:6];
      6'b??1???:
        _33_ = b[11:9];
      6'b?1????:
        _33_ = b[14:12];
      6'b1?????:
        _33_ = b[17:15];
      default:
        _33_ = a;
    endcase
  endfunction
  assign next_state = _33_(3'h0, { _00_, _01_, _02_, _03_, _04_, _05_ }, { _16_, _15_, _20_, _19_, _18_, _17_ });
  assign _17_ = current_state == 3'h5;
  assign _18_ = current_state == 3'h4;
  assign _19_ = current_state == 3'h3;
  assign _20_ = current_state == 3'h2;
  assign _15_ = current_state == 3'h1;
  assign _16_ = ! current_state;
  assign EW_RED = _14_ ? 1'h0 : 1'h1;
  assign NS_GREEN = _16_ ? 1'h1 : 1'h0;
  assign EW_GREEN = _19_ ? 1'h1 : 1'h0;
  assign EW_YELLOW = _18_ ? 1'h1 : 1'h0;
  assign NS_YELLOW = _15_ ? 1'h1 : 1'h0;
  assign NS_RED = _13_ ? 1'h0 : 1'h1;
  assign _05_ = timer_done ? 3'h0 : 3'hx;
  assign _04_ = timer_done ? 3'h5 : 3'hx;
  assign _03_ = timer_done ? 3'h4 : 3'hx;
  assign _02_ = timer_done ? 3'h3 : 3'hx;
endmodule

module traffic_light_controller(clk, reset, NS_RED, NS_YELLOW, NS_GREEN, EW_RED, EW_YELLOW, EW_GREEN);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  output EW_GREEN;
  wire EW_GREEN;
  output EW_RED;
  wire EW_RED;
  output EW_YELLOW;
  wire EW_YELLOW;
  output NS_GREEN;
  wire NS_GREEN;
  output NS_RED;
  wire NS_RED;
  output NS_YELLOW;
  wire NS_YELLOW;
  input clk;
  wire clk;
  wire [2:0] current_state;
  input reset;
  wire reset;
  wire timer_done;
  wire [7:0] timer_limit;
  assign _00_ = | { _02_, _04_ };
  assign _01_ = | { _05_, _03_ };
  function [7:0] _08_;
    input [7:0] a;
    input [15:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _08_ = b[7:0];
      2'b1?:
        _08_ = b[15:8];
      default:
        _08_ = a;
    endcase
  endfunction
  assign timer_limit = _08_(8'h02, 16'h0a03, { _01_, _00_ });
  assign _02_ = current_state == 3'h4;
  assign _03_ = current_state == 3'h3;
  assign _04_ = current_state == 3'h1;
  assign _05_ = ! current_state;
  traffic_fsm u_traffic_fsm (
    .EW_GREEN(EW_GREEN),
    .EW_RED(EW_RED),
    .EW_YELLOW(EW_YELLOW),
    .NS_GREEN(NS_GREEN),
    .NS_RED(NS_RED),
    .NS_YELLOW(NS_YELLOW),
    .clk(clk),
    .current_state(current_state),
    .reset(reset),
    .timer_done(timer_done)
  );
  \$paramod\traffic_timer\WIDTH=s32'00000000000000000000000000001000  u_traffic_timer (
    .clk(clk),
    .reset(reset),
    .timer_done(timer_done),
    .timer_limit(timer_limit)
  );
endmodule
